"""
Updated benchmark notebook creator for 20-sample evaluation.
Creates synthetic_evaluation_benchmark.ipynb with:
  - Dataset loading
  - Model loading (DocLayoutYOLO + Nemotron)
  - Inference loop with timing
  - Overall + per-domain metrics tables
  - Per-class heatmaps
  - Visual overlays (GT vs DocLayoutYOLO vs Nemotron)
  - Timing summary

Usage:
    cd medical-document-layout-annotator
    venv\Scripts\python.exe scratch\create_notebook.py
"""
import json
import os

notebook = {
 "cells": [
  # ── Cell 0: Markdown intro ──
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Synthetic Layout Ground-Truth Evaluation Benchmark\n",
    "\n",
    "This notebook evaluates **DocLayoutYOLO** (via Docling) and **NVIDIA Nemotron-Parse-v1.1** against\n",
    "**pixel-perfect, rendering-time ground-truth annotations** from the `synthetic_layout_gen` pipeline.\n",
    "\n",
    "**Dataset:** 2 samples × 5 domains (subset of Financial Invoice, Scientific Paper, Legal Opinion, Medical Report, Commercial Catalog)\n",
    "\n",
    "**Layout Skeleton Integration:** Generators now use empirical layout statistics harvested from DocLayNet\n",
    "instead of hardcoded margins, producing more realistic document geometries.\n",
    "\n",
    "## Metrics\n",
    "- **mAP@50** — Mean Average Precision at IoU 0.50\n",
    "- **mAP@50:95** — Mean AP averaged over IoU thresholds [0.50, 0.55, …, 0.95]\n",
    "- **Precision / Recall / F1** — at IoU 0.50\n",
    "- **mean_IoU** — Average IoU of matched predictions"
   ]
  },
  # ── Cell 1: Imports + Device ──
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "import glob\n",
    "import json\n",
    "import time\n",
    "import warnings\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from PIL import Image, ImageDraw\n",
    "import torch\n",
    "\n",
    "sys.path.insert(0, os.path.abspath(\".\"))\n",
    "\n",
    "from synthetic_layout_gen.core.canonical_taxonomy import CANONICAL_LABELS\n",
    "from backend.benchmark import (\n",
    "    DOCLAYNET_TO_CANONICAL,\n",
    "    compute_map\n",
    ")\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "print(f\"Device: {DEVICE}\")"
   ]
  },
  # ── Cell 2: Load dataset ──
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_synthetic_dataset(output_root=\"output/\"):\n",
    "    domains = [\"financial_invoice\", \"scientific_paper\", \"legal_opinion\", \"medical_report\", \"commercial_catalog\"]\n",
    "    samples = []\n",
    "    \n",
    "    for domain in domains:\n",
    "        json_pattern = os.path.join(output_root, domain, \"json\", \"*_0000[0-1].json\")\n",
    "        json_files = sorted(glob.glob(json_pattern))\n",
    "        \n",
    "        for json_path in json_files:\n",
    "            with open(json_path, \"r\", encoding=\"utf-8\") as f:\n",
    "                data = json.load(f)\n",
    "            \n",
    "            document_id = data[\"document_id\"]\n",
    "            for page in data[\"pages\"]:\n",
    "                image_rel_path = page[\"image_path\"]\n",
    "                image_abs_path = os.path.abspath(image_rel_path)\n",
    "                pdf_path = os.path.join(output_root, domain, \"pdfs\", f\"{document_id}.pdf\")\n",
    "                \n",
    "                gt_boxes = []\n",
    "                for elem in page[\"layout_elements\"]:\n",
    "                    gt_boxes.append({\n",
    "                        \"bbox\": elem[\"bbox\"],\n",
    "                        \"label\": elem[\"type\"]\n",
    "                    })\n",
    "                \n",
    "                samples.append({\n",
    "                    \"document_id\": document_id,\n",
    "                    \"domain\": domain,\n",
    "                    \"page_number\": page[\"page_number\"],\n",
    "                    \"image_path\": image_abs_path,\n",
    "                    \"pdf_path\": pdf_path,\n",
    "                    \"gt\": gt_boxes,\n",
    "                    \"dimensions_pt\": page[\"dimensions_pt\"]\n",
    "                })\n",
    "    return samples\n",
    "\n",
    "samples = load_synthetic_dataset()\n",
    "print(f\"Loaded {len(samples)} synthetic pages for evaluation.\")\n",
    "\n",
    "# Dataset summary\n",
    "from collections import Counter\n",
    "domain_counts = Counter(s['domain'] for s in samples)\n",
    "print(\"\\nPages per domain:\")\n",
    "for d, c in sorted(domain_counts.items()):\n",
    "    print(f\"  {d}: {c} pages\")\n",
    "print(f\"\\nTotal GT elements: {sum(len(s['gt']) for s in samples)}\")"
   ]
  },
  # ── Cell 3: Load models ──
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "from docling.document_converter import DocumentConverter, PdfFormatOption\n",
    "from docling.datamodel.base_models import InputFormat\n",
    "from docling.datamodel.pipeline_options import PdfPipelineOptions\n",
    "from transformers import AutoModel, AutoProcessor, AutoTokenizer, GenerationConfig\n",
    "\n",
    "print(\"Loading DocLayoutYOLO...\")\n",
    "pipeline_options = PdfPipelineOptions()\n",
    "pipeline_options.do_table_structure = True\n",
    "converter = DocumentConverter(\n",
    "    format_options={\n",
    "        InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)\n",
    "    }\n",
    ")\n",
    "print(\"DocLayoutYOLO loaded.\")\n",
    "\n",
    "print(\"Loading NVIDIA Nemotron-Parse-v1.1...\")\n",
    "MODEL_PATH = 'nvidia/NVIDIA-Nemotron-Parse-v1.1'\n",
    "nemo_model = AutoModel.from_pretrained(\n",
    "    MODEL_PATH,\n",
    "    trust_remote_code = True,\n",
    "    torch_dtype       = torch.float16,\n",
    "    low_cpu_mem_usage = True,\n",
    ").to(DEVICE).eval()\n",
    "\n",
    "nemo_tokenizer  = AutoTokenizer.from_pretrained(MODEL_PATH, use_fast=True)\n",
    "nemo_processor  = AutoProcessor.from_pretrained(MODEL_PATH, trust_remote_code=True, use_fast=True)\n",
    "nemo_processor.image_processor.final_size = (1024, 832)\n",
    "nemo_processor.image_processor._create_transforms()\n",
    "nemo_gen_config = GenerationConfig.from_pretrained(MODEL_PATH, trust_remote_code=True)\n",
    "nemo_gen_config.max_new_tokens = 1024\n",
    "print(\"Nemotron-Parse loaded.\")"
   ]
  },
  # ── Cell 4: Inference functions ──
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import re\n",
    "\n",
    "PROC_W = 832\n",
    "PROC_H = 1024\n",
    "BLOCK_PATTERN = re.compile(\n",
    "    r'<x_([0-9.]+)><y_([0-9.]+)>'   # top-left\n",
    "    r'(.*?)'                          # text content\n",
    "    r'<x_([0-9.]+)><y_([0-9.]+)>'   # bottom-right\n",
    "    r'<class_([^>]+)>',              # class label\n",
    "    re.DOTALL\n",
    ")\n",
    "\n",
    "def run_docling_on_pdf(pdf_path, page_number):\n",
    "    try:\n",
    "        result = converter.convert(pdf_path)\n",
    "        doc_obj = result.document\n",
    "        page_info = doc_obj.pages.get(page_number)\n",
    "        pw_pt, ph_pt = (page_info.size.width, page_info.size.height) if page_info and page_info.size else (612.0, 792.0)\n",
    "        \n",
    "        preds = []\n",
    "        for item, _ in doc_obj.iterate_items():\n",
    "            if not hasattr(item, 'prov') or not item.prov:\n",
    "                continue\n",
    "            prov = item.prov[0]\n",
    "            if prov.page_no != page_number:\n",
    "                continue\n",
    "            bbox = prov.bbox\n",
    "            label_raw = type(item).__name__.lower().replace('item', '').replace('docling', '')\n",
    "            canonical = DOCLAYNET_TO_CANONICAL.get(label_raw, 'text')\n",
    "            \n",
    "            x0, y0 = bbox.l, ph_pt - bbox.t\n",
    "            x1, y1 = bbox.r, ph_pt - bbox.b\n",
    "            x0, x1 = min(x0, x1), max(x0, x1)\n",
    "            y0, y1 = min(y0, y1), max(y0, y1)\n",
    "            \n",
    "            preds.append({\n",
    "                'bbox': [x0, y0, x1, y1],\n",
    "                'label': canonical,\n",
    "                'score': 0.9\n",
    "            })\n",
    "        return preds\n",
    "    except Exception as e:\n",
    "        print(f\"    Docling error: {e}\")\n",
    "        return []\n",
    "\n",
    "def run_nemotron_on_page(image_path, dpi=150):\n",
    "    pil_image = Image.open(image_path).convert(\"RGB\")\n",
    "    orig_w, orig_h = pil_image.size\n",
    "    \n",
    "    padded = Image.new('RGB', (PROC_W, PROC_H), (255, 255, 255))\n",
    "    if orig_w > PROC_W or orig_h > PROC_H:\n",
    "        scale = min(PROC_W / orig_w, PROC_H / orig_h)\n",
    "        new_w, new_h = int(orig_w * scale), int(orig_h * scale)\n",
    "        resized = pil_image.resize((new_w, new_h), Image.LANCZOS)\n",
    "        pad_x = (PROC_W - new_w) // 2\n",
    "        pad_y = (PROC_H - new_h) // 2\n",
    "        padded.paste(resized, (pad_x, pad_y))\n",
    "        effective_scale = scale\n",
    "    else:\n",
    "        pad_x = (PROC_W - orig_w) // 2\n",
    "        pad_y = (PROC_H - orig_h) // 2\n",
    "        padded.paste(pil_image, (pad_x, pad_y))\n",
    "        effective_scale = 1.0\n",
    "        \n",
    "    task_prompt = '</s><s><predict_bbox><predict_classes>'\n",
    "    inputs = nemo_processor(images=padded, text=task_prompt, return_tensors='pt', add_special_tokens=False).to(DEVICE)\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        outputs = nemo_model.generate(**inputs, generation_config=nemo_gen_config, max_new_tokens=1024)\n",
    "        \n",
    "    decoded = nemo_tokenizer.decode(outputs[0], skip_special_tokens=False)\n",
    "    \n",
    "    detections = []\n",
    "    for m in BLOCK_PATTERN.finditer(decoded):\n",
    "        x0_n, y0_n = float(m.group(1)), float(m.group(2))\n",
    "        x1_n, y1_n = float(m.group(4)), float(m.group(5))\n",
    "        cls = m.group(6).strip()\n",
    "        \n",
    "        x0_px = x0_n * PROC_W - pad_x\n",
    "        y0_px = y0_n * PROC_H - pad_y\n",
    "        x1_px = x1_n * PROC_W - pad_x\n",
    "        y1_px = y1_n * PROC_H - pad_y\n",
    "        \n",
    "        if effective_scale != 1.0:\n",
    "            x0_px /= effective_scale; y0_px /= effective_scale\n",
    "            x1_px /= effective_scale; y1_px /= effective_scale\n",
    "            \n",
    "        x0_px = max(0, min(orig_w, x0_px))\n",
    "        y0_px = max(0, min(orig_h, y0_px))\n",
    "        x1_px = max(0, min(orig_w, x1_px))\n",
    "        y1_px = max(0, min(orig_h, y1_px))\n",
    "        \n",
    "        canonical = DOCLAYNET_TO_CANONICAL.get(cls, DOCLAYNET_TO_CANONICAL.get(cls.lower(), 'text'))\n",
    "        \n",
    "        x0_pt = x0_px * 72.0 / dpi\n",
    "        y0_pt = y0_px * 72.0 / dpi\n",
    "        x1_pt = x1_px * 72.0 / dpi\n",
    "        y1_pt = y1_px * 72.0 / dpi\n",
    "        \n",
    "        if (x1_pt - x0_pt) > 1 and (y1_pt - y0_pt) > 1:\n",
    "            detections.append({\n",
    "                'bbox': [x0_pt, y0_pt, x1_pt, y1_pt],\n",
    "                'label': canonical,\n",
    "                'score': 0.85\n",
    "            })\n",
    "    return detections"
   ]
  },
  # ── Cell 5: Run inference with timing ──
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Running benchmark inference across all domains...\")\n",
    "all_gts = []\n",
    "docling_preds = []\n",
    "nemotron_preds = []\n",
    "docling_times = []\n",
    "nemotron_times = []\n",
    "\n",
    "t0 = time.time()\n",
    "for idx, s in enumerate(samples):\n",
    "    print(f\"[{idx+1}/{len(samples)}] Processing {s['document_id']} Page {s['page_number']}...\")\n",
    "    \n",
    "    # DocLayoutYOLO\n",
    "    t_dl = time.time()\n",
    "    dl_det = run_docling_on_pdf(s['pdf_path'], s['page_number'])\n",
    "    docling_times.append(time.time() - t_dl)\n",
    "    docling_preds.append(dl_det)\n",
    "    \n",
    "    # Nemotron\n",
    "    t_nm = time.time()\n",
    "    nm_det = run_nemotron_on_page(s['image_path'])\n",
    "    nemotron_times.append(time.time() - t_nm)\n",
    "    nemotron_preds.append(nm_det)\n",
    "    \n",
    "    all_gts.append(s['gt'])\n",
    "\n",
    "total_time = time.time() - t0\n",
    "print(f\"\\nFinished evaluation loop in {total_time:.1f}s.\")\n",
    "print(f\"  DocLayoutYOLO avg: {np.mean(docling_times):.2f}s/page ({len(samples)/sum(docling_times):.2f} pages/sec)\")\n",
    "print(f\"  Nemotron avg:      {np.mean(nemotron_times):.2f}s/page ({len(samples)/sum(nemotron_times):.2f} pages/sec)\")"
   ]
  },
  # ── Cell 6: Overall metrics ──
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Overall Benchmark Results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "iou_thresholds = np.linspace(0.5, 0.95, 10)\n",
    "valid_classes = set(CANONICAL_LABELS)\n",
    "\n",
    "dl_metrics = compute_map(all_gts, docling_preds, iou_thresholds, valid_classes)\n",
    "nm_metrics = compute_map(all_gts, nemotron_preds, iou_thresholds, valid_classes)\n",
    "\n",
    "rows = []\n",
    "for model_name, metrics, times in [\n",
    "    (\"DocLayoutYOLO\", dl_metrics, docling_times),\n",
    "    (\"Nemotron-Parse\", nm_metrics, nemotron_times)\n",
    "]:\n",
    "    rows.append({\n",
    "        \"Model\": model_name,\n",
    "        \"mAP@50\": metrics[\"mAP50\"],\n",
    "        \"mAP@50:95\": metrics[\"mAP5095\"],\n",
    "        \"Precision\": metrics[\"precision\"],\n",
    "        \"Recall\": metrics[\"recall\"],\n",
    "        \"F1-Score\": metrics[\"F1\"],\n",
    "        \"mean_IoU\": metrics[\"mean_iou\"],\n",
    "        \"Avg Time (s/page)\": np.mean(times),\n",
    "        \"Pages/sec\": len(samples) / sum(times),\n",
    "    })\n",
    "\n",
    "df_results = pd.DataFrame(rows).set_index(\"Model\")\n",
    "display(df_results.style.format('{:.3f}').set_caption(\n",
    "    f'Overall Benchmark — {len(samples)} pages × 5 domains × 2 models'))"
   ]
  },
  # ── Cell 7: Domain breakdown ──
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Domain-Specific Results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "domain_results = []\n",
    "domains_list = sorted(list(set(s['domain'] for s in samples)))\n",
    "\n",
    "for domain in domains_list:\n",
    "    indices = [i for i, s in enumerate(samples) if s['domain'] == domain]\n",
    "    domain_gts = [all_gts[i] for i in indices]\n",
    "    domain_dl = [docling_preds[i] for i in indices]\n",
    "    domain_nm = [nemotron_preds[i] for i in indices]\n",
    "    \n",
    "    dl_dom_m = compute_map(domain_gts, domain_dl, iou_thresholds, valid_classes)\n",
    "    nm_dom_m = compute_map(domain_gts, domain_nm, iou_thresholds, valid_classes)\n",
    "    \n",
    "    for model, met in [(\"DocLayoutYOLO\", dl_dom_m), (\"Nemotron-Parse\", nm_dom_m)]:\n",
    "        domain_results.append({\n",
    "            \"Domain\": domain.replace('_', ' ').title(),\n",
    "            \"Model\": model,\n",
    "            \"mAP@50\": met[\"mAP50\"],\n",
    "            \"mAP@50:95\": met[\"mAP5095\"],\n",
    "            \"Precision\": met[\"precision\"],\n",
    "            \"Recall\": met[\"recall\"],\n",
    "            \"F1-Score\": met[\"F1\"],\n",
    "            \"mean_IoU\": met[\"mean_iou\"]\n",
    "        })\n",
    "\n",
    "df_domains = pd.DataFrame(domain_results).set_index([\"Domain\", \"Model\"])\n",
    "display(df_domains.style.format('{:.3f}').set_caption('Per-Domain Breakdown'))"
   ]
  },
  # ── Cell 8: Bar chart ──
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## mAP@50:95 Comparison by Domain"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_plot = pd.DataFrame(domain_results)\n",
    "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
    "\n",
    "for ax, metric, title in zip(axes, ['mAP@50:95', 'F1-Score', 'mean_IoU'],\n",
    "                                   ['mAP@50:95', 'F1-Score', 'Mean IoU']):\n",
    "    sns.barplot(data=df_plot, x='Domain', y=metric, hue='Model', palette='muted', ax=ax)\n",
    "    ax.set_title(f'{title} by Domain', fontweight='bold')\n",
    "    ax.set_ylabel(title)\n",
    "    ax.set_xlabel('')\n",
    "    ax.set_ylim(0, 1.0)\n",
    "    ax.grid(axis='y', linestyle='--', alpha=0.7)\n",
    "    ax.tick_params(axis='x', rotation=25)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('benchmark_output/domain_comparison.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  # ── Cell 9: Per-class heatmap ──
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Per-Class Precision Heatmap (at IoU 0.50)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "os.makedirs('benchmark_output', exist_ok=True)\n",
    "\n",
    "# Collect per-class AP from overall metrics\n",
    "classes = sorted(list(valid_classes))\n",
    "models = ['DocLayoutYOLO', 'Nemotron-Parse']\n",
    "all_metrics = [dl_metrics, nm_metrics]\n",
    "\n",
    "data = []\n",
    "for cls in classes:\n",
    "    row = []\n",
    "    for met in all_metrics:\n",
    "        row.append(met.get('ap50_per_class', {}).get(cls, 0))\n",
    "    data.append(row)\n",
    "\n",
    "hm_df = pd.DataFrame(data, index=classes, columns=models)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(8, 8))\n",
    "sns.heatmap(hm_df, annot=True, fmt='.3f', cmap='RdYlGn',\n",
    "            linewidths=.5, vmin=0, vmax=1, ax=ax,\n",
    "            cbar_kws={'label': 'Precision @ IoU 0.50'})\n",
    "ax.set_title('Per-Class Precision @ IoU 0.50 — Synthetic GT', fontsize=13, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig('benchmark_output/perclass_heatmap.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  # ── Cell 10: Visual overlays ──
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Visual Comparison: GT vs. DocLayoutYOLO vs. Nemotron-Parse\n",
    "\n",
    "One sample from each domain showing ground-truth annotations alongside model predictions."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "color_map = {\n",
    "    'title': '#e63946', 'section_header': '#ff6b35', 'text': '#457b9d',\n",
    "    'list_item': '#2a9d8f', 'table': '#e9c46a', 'picture': '#f4a261',\n",
    "    'caption': '#8ecae6', 'footnote': '#a8dadc', 'formula': '#6d6875',\n",
    "    'page_header': '#b5838d', 'page_footer': '#e5989b'\n",
    "}\n",
    "\n",
    "fig, axes = plt.subplots(len(domains_list), 3, figsize=(18, 6 * len(domains_list)))\n",
    "\n",
    "for d_idx, domain in enumerate(domains_list):\n",
    "    sample_idx = next(i for i, s in enumerate(samples) if s['domain'] == domain)\n",
    "    s = samples[sample_idx]\n",
    "    \n",
    "    img = Image.open(s['image_path']).convert(\"RGB\")\n",
    "    \n",
    "    def draw_on_img(pil_img, detections, cmap, dpi=150):\n",
    "        draw_img = pil_img.copy()\n",
    "        draw = ImageDraw.Draw(draw_img)\n",
    "        for d in detections:\n",
    "            x0, y0, x1, y1 = d['bbox']\n",
    "            x0_px = x0 * dpi / 72.0\n",
    "            y0_px = y0 * dpi / 72.0\n",
    "            x1_px = x1 * dpi / 72.0\n",
    "            y1_px = y1 * dpi / 72.0\n",
    "            draw.rectangle([x0_px, y0_px, x1_px, y1_px],\n",
    "                           outline=cmap.get(d['label'], '#888888'), width=3)\n",
    "        return draw_img\n",
    "    \n",
    "    gt_drawn = draw_on_img(img, s['gt'], color_map)\n",
    "    dl_drawn = draw_on_img(img, docling_preds[sample_idx], color_map)\n",
    "    nm_drawn = draw_on_img(img, nemotron_preds[sample_idx], color_map)\n",
    "    \n",
    "    display_name = domain.replace('_', ' ').title()\n",
    "    axes[d_idx, 0].imshow(gt_drawn)\n",
    "    axes[d_idx, 0].set_title(f\"{display_name} — Ground Truth ({len(s['gt'])} elements)\")\n",
    "    axes[d_idx, 0].axis(\"off\")\n",
    "    \n",
    "    axes[d_idx, 1].imshow(dl_drawn)\n",
    "    axes[d_idx, 1].set_title(f\"{display_name} — DocLayoutYOLO ({len(docling_preds[sample_idx])} detections)\")\n",
    "    axes[d_idx, 1].axis(\"off\")\n",
    "    \n",
    "    axes[d_idx, 2].imshow(nm_drawn)\n",
    "    axes[d_idx, 2].set_title(f\"{display_name} — Nemotron-Parse ({len(nemotron_preds[sample_idx])} detections)\")\n",
    "    axes[d_idx, 2].axis(\"off\")\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('benchmark_output/visual_comparison.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  # ── Cell 11: Timing summary ──
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Timing Summary"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "timing_data = {\n",
    "    'Model': ['DocLayoutYOLO', 'Nemotron-Parse'],\n",
    "    'Total Time (s)': [sum(docling_times), sum(nemotron_times)],\n",
    "    'Avg per Page (s)': [np.mean(docling_times), np.mean(nemotron_times)],\n",
    "    'Median per Page (s)': [np.median(docling_times), np.median(nemotron_times)],\n",
    "    'Pages/sec': [len(samples)/sum(docling_times), len(samples)/sum(nemotron_times)],\n",
    "}\n",
    "df_timing = pd.DataFrame(timing_data).set_index('Model')\n",
    "display(df_timing.style.format('{:.3f}').set_caption('Inference Timing'))\n",
    "\n",
    "# Per-domain timing\n",
    "domain_timing = []\n",
    "for domain in domains_list:\n",
    "    indices = [i for i, s in enumerate(samples) if s['domain'] == domain]\n",
    "    dl_t = np.mean([docling_times[i] for i in indices])\n",
    "    nm_t = np.mean([nemotron_times[i] for i in indices])\n",
    "    domain_timing.append({'Domain': domain.replace('_', ' ').title(),\n",
    "                          'DocLayoutYOLO (s/page)': dl_t,\n",
    "                          'Nemotron (s/page)': nm_t})\n",
    "\n",
    "df_dom_timing = pd.DataFrame(domain_timing).set_index('Domain')\n",
    "display(df_dom_timing.style.format('{:.2f}').set_caption('Per-Domain Average Inference Time'))"
   ]
  },
  # ── Cell 12: Save results ──
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Save results to CSV\n",
    "os.makedirs('benchmark_output', exist_ok=True)\n",
    "df_results.to_csv('benchmark_output/overall_results.csv')\n",
    "df_domains.to_csv('benchmark_output/domain_results.csv')\n",
    "df_timing.to_csv('benchmark_output/timing_results.csv')\n",
    "print(\"Results saved to benchmark_output/\")\n",
    "print(\"\\n\" + \"=\"*60)\n",
    "print(\"BENCHMARK COMPLETE\")\n",
    "print(f\"Total pages evaluated: {len(samples)}\")\n",
    "print(f\"Total time: {total_time:.1f}s\")\n",
    "print(\"=\"*60)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

# Write ipynb
out_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "synthetic_evaluation_benchmark.ipynb"))
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)
print(f"Jupyter notebook written to {out_path}")
